# Simulating Coin Flips

In [1]:
import numpy as np

In [2]:
# outcome of one coin flip
np.random.randint(2)

0

In [3]:
# outcomes of ten thousand coin flips
np.random.randint(2, size=10000)

array([1, 0, 1, ..., 1, 0, 0])

In [4]:
# mean outcome of ten thousand coin flips
np.random.randint(2, size=10000).mean()

0.5005

In [5]:
# outcome of one coin flip
np.random.choice([0, 1])

1

In [6]:
# outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000)

array([1, 1, 0, ..., 1, 0, 1])

In [7]:
# mean outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000).mean()

0.5003

In [8]:
# outcomes of ten thousand biased coin flips
np.random.choice([0, 1], size=10000, p=[0.8, 0.2])

array([0, 0, 0, ..., 0, 0, 1])

In [9]:
# mean outcome of ten thousand biased coin flips
np.random.choice([0, 1], size=10000, p=[0.8, 0.2]).mean()

0.2023

In [11]:
np.random.randint(0,2, size =10000).mean()

0.5013

In [ ]:
np.random.choice([0,1], size =10, p=[0.8,0.2]).mean()